/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/analytics/vendors/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List vendors
         * @description Returns a clean array containing all registered vendor compliance rows.
         */
        get: operations["vendor_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/vendors/{vendor_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve a vendor compliance profile
         * @description Fetches the complete compliance ledger, including data categories, legal bounds, and linked document artifacts.
         */
        get: operations["vendor_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/vendors/{vendor_id}/predict/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Predict vendor anomaly risk
         * @description Runs the anomaly model for a vendor registry record and returns the predicted class plus class probabilities.
         */
        get: operations["vendor_risk_prediction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schema/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description OpenApi3 schema for this API. Format can be selected via content negotiation.
         *
         *     - YAML: application/vnd.oai.openapi
         *     - JSON: application/vnd.oai.openapi+json
         */
        get: operations["schema_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vendors/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create vendor assessment
         * @description Uploads documents and starts asynchronous compliance analysis.
         */
        post: operations["vendor-ingestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `PENDING` - Pending Assessment
         *     * `PROCESSING` - Processing Ingestion Pipeline
         *     * `VERIFIED` - Verified Low Risk
         *     * `CONDITIONAL` - Conditional Medium Risk
         *     * `QUARANTINED` - Critical High Risk Action Required
         * @enum {string}
         */
        CurrentStatusEnum: "PENDING" | "PROCESSING" | "VERIFIED" | "CONDITIONAL" | "QUARANTINED";
        /**
         * @description * `PCI_CARDHOLDER_DATA` - Credit Card Details / PAN / CVV
         *     * `CUSTOMER_PII` - Personally Identifiable Info (Names, Addresses)
         *     * `CREDENTIALS_AUTH` - Authentication Hashes / API Tokens
         *     * `FINANCIAL_RECORDS` - Corporate Accounting / Trade Ledger Data
         *     * `PUBLIC_MARKETING` - Publicly Available Marketing Assets
         * @enum {string}
         */
        DeclaredDataCategoriesEnum: "PCI_CARDHOLDER_DATA" | "CUSTOMER_PII" | "CREDENTIALS_AUTH" | "FINANCIAL_RECORDS" | "PUBLIC_MARKETING";
        /**
         * @description * `MSA` - Master Services Agreement
         *     * `DPA` - Data Processing Addendum
         *     * `SOC2_TYPE2` - SOC 2 Type II Compliance Report
         *     * `PCI_DSS_AOC` - PCI-DSS Attestation of Compliance
         * @enum {string}
         */
        DocumentTypeEnum: "MSA" | "DPA" | "SOC2_TYPE2" | "PCI_DSS_AOC";
        ErrorResponse: {
            detail?: string;
            error?: string;
        };
        /**
         * @description * `PENDING` - Pending Engine Queue
         *     * `SUCCESS` - Parsed and Validated
         *     * `FAILED` - Pipeline Error Processing File
         * @enum {string}
         */
        ExtractionStatusEnum: "PENDING" | "SUCCESS" | "FAILED";
        /**
         * @description * `PENDING` - Pending Assessment
         *     * `PROCESSING` - Processing Ingestion Pipeline
         *     * `VERIFIED` - Verified Low Risk
         *     * `CONDITIONAL` - Conditional Medium Risk
         *     * `QUARANTINED` - Critical High Risk Action Required
         * @enum {string}
         */
        StatusEnum: "PENDING" | "PROCESSING" | "VERIFIED" | "CONDITIONAL" | "QUARANTINED";
        VendorDetail: {
            /** Format: uuid */
            readonly vendor_id: string;
            readonly status: components["schemas"]["StatusEnum"];
            readonly declared_data_categories: components["schemas"]["DeclaredDataCategoriesEnum"][];
            readonly declared_systems_accessed: string[];
            readonly documents: components["schemas"]["VendorDocument"][];
            /** Format: uri */
            readonly execution_trace_log: string;
            /** @description Official legal corporate name of the vendor entity. */
            vendor_name: string;
            /** @description Operational categorization. e.g., 'Cloud Storage Provider'. */
            vendor_type: string;
            /** @description Internal enterprise manager overseeing the relationship. */
            business_owner: string;
            /** Format: decimal */
            annual_spend?: string | null;
            /**
             * @description - contract_end_date, contract_start_date (ISO strings)
             *                 - breach_notification_hours (integer numbers)
             *                 - data_return_deadline_days (integer numbers)
             *                 - subprocessors_disclosed (array of text strings)
             *                 - data_categories_processed (array of text strings)
             *                 - liability_cap_usd (numeric float/integer value)
             *                 - liability_uncapped_for_security_breach (boolean)
             *                 - cert_termination_right (boolean)
             *                 - soc2_opinion_type ("qualified" or "unqualified")
             *                 - soc2_audit_period_end (ISO string)
             *                 - pci_dss_level (integer or string value)
             *                 - pci_assessor_type ("independent_qsa" or "self_assessed")
             */
            extracted_legal_bounds?: unknown;
            /**
             * @description Array of live discovered endpoint configurations. Expected structure:
             *     [
             *       {'system_name': 'prod-db-01', 'data_sensitivity': 'PCI_HIGH_CRITICALITY'}
             *     ]
             */
            discovered_infrastructure?: unknown;
            /** Format: decimal */
            current_risk_score?: string;
            /** Format: decimal */
            previous_risk_score?: string;
            /** @description AI-generated audit rationale explaining compliance exceptions or structural defects. */
            risk_narrative_summary?: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        VendorDocument: {
            /** Format: uuid */
            readonly document_id: string;
            readonly document_type: components["schemas"]["DocumentTypeEnum"];
            readonly extraction_status: components["schemas"]["ExtractionStatusEnum"];
            /** Format: date-time */
            readonly uploaded_at: string;
            readonly is_expired: boolean;
        };
        VendorIngestionRequestRequest: {
            /** @description Official legal corporate name of the vendor entity. */
            vendor_name: string;
            /** @description Operational categorization. e.g., 'Cloud Storage Provider'. */
            vendor_type: string;
            /** @description Internal enterprise manager overseeing the relationship. */
            business_owner: string;
            /** Format: decimal */
            annual_spend?: string | null;
            declared_data_categories?: components["schemas"]["DeclaredDataCategoriesEnum"][];
            declared_systems_accessed?: string;
            /** @description Upload files simultaneously. File names must contain structural keywords to match types correctly: 'MSA' for contracts, 'DPA' for privacy guidelines, 'SOC' for audits, or 'PCI'/'AOC' for processing compliance. */
            documents: string[];
        };
        VendorIngestionResponse: {
            message: string;
            /** Format: uuid */
            vendor_id: string;
            current_status: components["schemas"]["CurrentStatusEnum"];
        };
        VendorList: {
            /** Format: uuid */
            readonly vendor_id: string;
            /** @description Official legal corporate name of the vendor entity. */
            vendor_name: string;
            /** @description Operational categorization. e.g., 'Cloud Storage Provider'. */
            vendor_type: string;
            /** @description Internal enterprise manager overseeing the relationship. */
            business_owner: string;
            readonly status: components["schemas"]["StatusEnum"];
            /** Format: decimal */
            current_risk_score?: string;
            /** Format: decimal */
            previous_risk_score?: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        VendorRiskPredictionResponse: {
            vendor_id: string;
            vendor_name: string;
            is_anomaly: boolean;
            anomaly_type: string;
            /** Format: double */
            confidence: number;
            all_probs: {
                [key: string]: number;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    vendor_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VendorList"][];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    vendor_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique database UUID identifying the target vendor record. */
                vendor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VendorDetail"];
                };
            };
            /** @description The specified vendor UUID does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    vendor_risk_prediction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Vendor registry UUID. */
                vendor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VendorRiskPredictionResponse"];
                };
            };
            /** @description Vendor not found in registry. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unexpected model or inference failure. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    schema_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "yaml";
                lang?: "af" | "ar" | "ar-dz" | "ast" | "az" | "be" | "bg" | "bn" | "br" | "bs" | "ca" | "ckb" | "cs" | "cy" | "da" | "de" | "dsb" | "el" | "en" | "en-au" | "en-gb" | "eo" | "es" | "es-ar" | "es-co" | "es-mx" | "es-ni" | "es-ve" | "et" | "eu" | "fa" | "fi" | "fr" | "fy" | "ga" | "gd" | "gl" | "he" | "hi" | "hr" | "hsb" | "ht" | "hu" | "hy" | "ia" | "id" | "ig" | "io" | "is" | "it" | "ja" | "ka" | "kab" | "kk" | "km" | "kn" | "ko" | "ky" | "lb" | "lt" | "lv" | "mk" | "ml" | "mn" | "mr" | "ms" | "my" | "nb" | "ne" | "nl" | "nn" | "os" | "pa" | "pl" | "pt" | "pt-br" | "ro" | "ru" | "sk" | "sl" | "sq" | "sr" | "sr-latn" | "sv" | "sw" | "ta" | "te" | "tg" | "th" | "tk" | "tr" | "tt" | "udm" | "ug" | "uk" | "ur" | "uz" | "vi" | "zh-hans" | "zh-hant";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.oai.openapi": {
                        [key: string]: unknown;
                    };
                    "application/yaml": {
                        [key: string]: unknown;
                    };
                    "application/vnd.oai.openapi+json": {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    "vendor-ingestion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["VendorIngestionRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["VendorIngestionRequestRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VendorIngestionResponse"];
                };
            };
        };
    };
}
