# Generated by Django 6.0.6 on 2026-06-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorRegistry',
            fields=[
                ('vendor_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=255)),
                ('vendor_type', models.CharField(blank=True, max_length=128, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('compliance_certifications', models.TextField(blank=True, null=True)),
                ('data_access_scope', models.CharField(blank=True, max_length=128, null=True)),
                ('risk_score', models.FloatField()),
                ('breach_status', models.CharField(blank=True, max_length=128, null=True)),
                ('annual_spend', models.FloatField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('last_audit_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vendor_registry',
            },
        ),
    ]
