# Generated by Django 6.0.6 on 2026-06-20 19:55

import core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(help_text='Official legal corporate name of the vendor entity.', max_length=255, unique=True)),
                ('vendor_type', models.CharField(help_text="Operational categorization. e.g., 'Cloud Storage Provider'.", max_length=100)),
                ('business_owner', models.CharField(help_text='Internal enterprise manager overseeing the relationship.', max_length=255)),
                ('annual_spend', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PENDING_ASSESSMENT', 'Pending Assessment'), ('PROCESSING', 'Processing Ingestion Pipeline'), ('VERIFIED_GREEN', 'Verified Low Risk'), ('CONDITIONAL_YELLOW', 'Conditional Medium Risk'), ('QUARANTINED_RED', 'Critical High Risk Action Required')], default='PENDING_ASSESSMENT', max_length=30)),
                ('declared_data_categories', models.JSONField(blank=True, default=list, help_text='List of asset classes intended to be shared with this vendor.')),
                ('declared_systems_accessed', models.JSONField(blank=True, default=list, help_text='List of targeted system logical endpoints the vendor can access.')),
                ('extracted_legal_bounds', models.JSONField(blank=True, default=dict, help_text='Structured contract elements extracted from legal PDFs. Schema contains keys: contract_end_date (str/null), pci_assessor_type (str/null), soc2_has_qualified_opinion (bool/null), breach_notification_hours (int/null), and liability_cap_usd (float/null).')),
                ('discovered_infrastructure', models.JSONField(blank=True, default=list, help_text="Array of live discovered endpoint configurations. Expected structure:\n[\n  {'system_name': 'prod-db-01', 'data_sensitivity': 'PCI_HIGH_CRITICALITY'}\n]")),
                ('execution_trace_log', models.TextField(blank=True, default='', help_text='Stores machine-readable Obsidian-style log strings to generate UI dependency flow graphs.')),
                ('current_risk_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('previous_risk_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('risk_narrative_summary', models.TextField(blank=True, help_text='AI-generated audit rationale explaining compliance exceptions or structural defects.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vendor Profile Ledger',
                'indexes': [models.Index(fields=['status'], name='core_vendor_status_866d00_idx'), models.Index(fields=['current_risk_score'], name='core_vendor_current_62672e_idx')],
            },
        ),
        migrations.CreateModel(
            name='VendorDocument',
            fields=[
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('MSA', 'Master Services Agreement'), ('DPA', 'Data Processing Addendum'), ('SOC2_TYPE2', 'SOC 2 Type II Compliance Report'), ('PCI_DSS_AOC', 'PCI-DSS Attestation of Compliance')], max_length=30)),
                ('file', models.FileField(help_text='Path pointer targeting the raw file binary payload stored on disk.', upload_to=core.models.vendor_document_path_resolver)),
                ('document_reference', models.CharField(blank=True, help_text='Internal compliance cross-reference tracking tracking hash.', max_length=100)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('extraction_status', models.CharField(choices=[('PENDING', 'Pending Engine Queue'), ('SUCCESS', 'Parsed and Validated'), ('FAILED', 'Pipeline Error Processing File')], default='PENDING', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.vendor')),
            ],
        ),
    ]
