# Generated by Django 6.0.6 on 2026-06-20 14:24

import core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(help_text="Official corporate legal name. Example: 'NimbusPay LLC'", max_length=255, unique=True)),
                ('vendor_type', models.CharField(help_text="Operational grouping. Example: 'Payment Gateway', 'Cloud Infra Storage'", max_length=100)),
                ('business_owner', models.CharField(help_text="Internal bank manager monitoring this relationship. Example: 'John Doe (Treasury Desk)'", max_length=255)),
                ('annual_spend', models.DecimalField(blank=True, decimal_places=2, help_text='Used to measure financial criticality. Example: 1250000.00', max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PENDING_ASSESSMENT', 'Pending Assessment'), ('PROCESSING', 'Processing Ingestion Pipeline'), ('VERIFIED_GREEN', 'Verified Low Risk'), ('CONDITIONAL_YELLOW', 'Conditional Medium Risk'), ('QUARANTINED_RED', 'Critical High Risk Action Required')], default='PENDING_ASSESSMENT', max_length=30)),
                ('declared_data_categories', models.JSONField(blank=True, default=list, help_text="List of asset classes requested. Expected items from Vendor.DataCategory enum. Example: ['CUSTOMER_PII', 'PCI_CARDHOLDER_DATA']")),
                ('declared_systems_accessed', models.JSONField(blank=True, default=list, help_text="List of logical technical target endpoints. Example: ['Core_Production_DB', 'Swift_Gateway_Network']")),
                ('compliance_payload', models.JSONField(blank=True, default=dict, help_text='Standardized schema populated via LLM extraction extraction containing keys like: contract_end_date (str), pci_assessor_type (str), soc2_has_qualified_opinion (bool), breach_notification_hours (int), and liability_cap_usd (float).')),
                ('current_risk_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated dynamic scale score from 0.00 (Zero Risk) to 100.00 (Extreme Risk)', max_digits=5)),
                ('previous_risk_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('risk_narrative_summary', models.TextField(blank=True, help_text='AI generated summary explaining the scoring logic or hidden defects caught by cross-checks.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vendor Profile Ledger',
                'indexes': [models.Index(fields=['status'], name='core_vendor_status_866d00_idx'), models.Index(fields=['current_risk_score'], name='core_vendor_current_62672e_idx')],
            },
        ),
        migrations.CreateModel(
            name='VendorAccessGrant',
            fields=[
                ('grant_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system_name', models.CharField(help_text="The technical target identified in corporate config. Example: 'prod-rds-cluster-01'", max_length=255)),
                ('data_sensitivity', models.CharField(choices=[('PCI_HIGH_CRITICALITY', 'Direct Production Card Environment Access'), ('RESTRICTED_PII', 'Internal Systems Handling Client Identity Records'), ('LOW_IMPACT_ZONE', 'General Purpose Sandbox or Corporate Chat Channel')], max_length=50)),
                ('access_type', models.CharField(help_text="The network strategy protocol used. Example: 'IAM_AWS_ROLE', 'OKTA_SAML_GROUP', 'SSH_KEY'", max_length=50)),
                ('grant_status', models.CharField(choices=[('ACTIVE', 'Active Provisioned Key Entity'), ('REVOKED', 'De-provisioned Safe Endpoint'), ('ORPHANED', 'Active Token Detected Without a Valid Underpining Contract')], default='ACTIVE', max_length=20)),
                ('last_used', models.DateTimeField(blank=True, help_text='Last detected network packet timestamps.', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, help_text='Timestamp when corporate directory severed the link.', null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='core.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorDocument',
            fields=[
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('MSA', 'Master Services Agreement'), ('DPA', 'Data Processing Addendum'), ('SOC2_TYPE2', 'SOC 2 Type II Compliance Report'), ('PCI_DSS_AOC', 'PCI-DSS Attestation of Compliance')], max_length=30)),
                ('file', models.FileField(help_text="Location pointer for raw binary. Example: 'vendor_compliance_vault/nimbus_pci.pdf'", upload_to=core.models.vendor_document_path)),
                ('document_reference', models.CharField(blank=True, help_text="Corporate document cross-reference tracking ID. Example: 'SG-MSA-2026-NIMBUS-09'", max_length=100)),
                ('issued_date', models.DateField(blank=True, help_text='Date signed or published. Example: 2026-01-01', null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Calculated date of expiration. Example: 2027-01-01', null=True)),
                ('extraction_status', models.CharField(choices=[('PENDING', 'Pending Engine Queue'), ('SUCCESS', 'Parsed and Validated'), ('FAILED', 'Pipeline Error Processing File')], default='PENDING', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.vendor')),
            ],
        ),
    ]
