# Generated by Django 5.2.15 on 2026-06-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='extracted_legal_bounds',
            field=models.JSONField(blank=True, default=dict, help_text='\n            - contract_end_date, contract_start_date (ISO strings)\n            - breach_notification_hours (integer numbers)\n            - data_return_deadline_days (integer numbers)\n            - subprocessors_disclosed (array of text strings)\n            - data_categories_processed (array of text strings)\n            - liability_cap_usd (numeric float/integer value)\n            - liability_uncapped_for_security_breach (boolean)\n            - cert_termination_right (boolean)\n            - soc2_opinion_type ("qualified" or "unqualified")\n            - soc2_audit_period_end (ISO string)\n            - pci_dss_level (integer or string value)\n            - pci_assessor_type ("independent_qsa" or "self_assessed")\n            '),
        ),
    ]
